services:

  graphdb:
    image: fairdatasystems/gdb:2026-02-11
    restart: always
    hostname: graphdb
    ports:
      - 127.0.0.1:7200:7200
    volumes:
      - ACME-graphdb:/opt/graphdb/home
    networks:
      - ACME-default

      
  transformation-daemon:
    image:  fairdatasystems/cdeb:2026-02-11    # to use the CARE-SM models with the care-sm-toolkit
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
      GRAPHDB_REPONAME: ${GRAPHDB_REPONAME}
    depends_on:
      - caresm
      - yarrrml-rdfizer
    ports:
      - 127.0.0.1:4567:4567
    volumes:
      - ./data:/data
    networks:
      - ACME-default

  caresm:
    image: saracuriel/care:1.0.0 #check latest tag at https://hub.docker.com/repository/docker/saracuriel/care/tags
    hostname: caresm
    volumes:
      - ./data:/data
    networks:
      - ACME-default

  yarrrml-rdfizer:
    image: fairdatasystems/yrml:2026-02-11
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
#    ports:
#      - "4567:4567"
    volumes:
      - ./data:/mnt/data
    networks:
      - ACME-default


volumes:
  ACME-graphdb:
    external: true

networks:
  ACME-default:
